In [2]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    "Order_ID":[101,102,103,104,105,106,107,108,109,110,
                111,112,113,114,115,116,117,118,119,120],

    "Customer":[
        "Ali","Sara","John","Emma","Ali",
        "Fatima","David","Kabir","Sara","John",
        "Emma","Ali","Fatima","David","Kabir",
        "Ali","Sara","John","Emma","Fatima"
    ],

    "City":[
        "Delhi","Delhi","Mumbai","Pune","Delhi",
        "Mumbai","Lucknow","Delhi","Pune","Mumbai",
        "Lucknow","Delhi","Mumbai","Delhi","Pune",
        "Delhi","Lucknow","Mumbai","Delhi","Pune"
    ],

    "Category":[
        "Laptop","Phone","Laptop","Phone","Tablet",
        "Laptop","Phone","Tablet","Laptop","Phone",
        "Tablet","Laptop","Phone","Laptop","Tablet",
        "Phone","Laptop","Tablet","Laptop","Phone"
    ],

    "Payment":[
        "UPI","Cash","Card","UPI","Card",
        "Cash","UPI","Card","Cash","UPI",
        "Card","UPI","Cash","UPI","Card",
        "Cash","UPI","Card","UPI","Cash"
    ],

    "Revenue":[
        70000,30000,80000,25000,40000,
        90000,20000,35000,60000,45000,
        30000,75000,40000,85000,32000,
        28000,78000,33000,72000,26000
    ],

    "Quantity":[
        2,3,1,2,4,
        2,1,5,2,3,
        2,1,2,2,4,
        2,1,3,2,2
    ],

    "Rating":[
        4.8,4.3,4.9,4.1,4.5,
        4.8,3.9,4.2,4.6,4.4,
        4.0,4.9,4.3,4.7,4.2,
        4.1,4.8,4.0,4.9,4.2
    ],

    "Order_Date":[
        "2025-01-10","2025-01-22","2025-02-11","2025-02-25",
        "2025-03-12","2025-03-29","2025-04-14","2025-04-25",
        "2025-05-18","2025-05-25","2025-06-05","2025-06-15",
        "2025-06-20","2025-06-28","2025-05-30","2025-03-18",
        "2025-04-02","2025-05-10","2025-06-22","2025-02-18"
    ]
})
df=orders.copy()
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df

,Order_ID,Customer,City,Category,Payment,Revenue,Quantity,Rating,Order_Date
0,101,Ali,Delhi,Laptop,UPI,70000,2,4.8,2025-01-10
1,102,Sara,Delhi,Phone,Cash,30000,3,4.3,2025-01-22
2,103,John,Mumbai,Laptop,Card,80000,1,4.9,2025-02-11
3,104,Emma,Pune,Phone,UPI,25000,2,4.1,2025-02-25
4,105,Ali,Delhi,Tablet,Card,40000,4,4.5,2025-03-12
5,106,Fatima,Mumbai,Laptop,Cash,90000,2,4.8,2025-03-29
6,107,David,Lucknow,Phone,UPI,20000,1,3.9,2025-04-14
7,108,Kabir,Delhi,Tablet,Card,35000,5,4.2,2025-04-25
8,109,Sara,Pune,Laptop,Cash,60000,2,4.6,2025-05-18
9,110,John,Mumbai,Phone,UPI,45000,3,4.4,2025-05-25
10,111,Emma,Lucknow,Tablet,Card,30000,2,4.0,2025-06-05
11,112,Ali,Delhi,Laptop,UPI,75000,1,4.9,2025-06-15
12,113,Fatima,Mumbai,Phone,Cash,40000,2,4.3,2025-06-20
13,114,David,Delhi,Laptop,UPI,85000,2,4.7,2025-06-28
14,115,Kabir,Pune,Tablet,Card,32000,4,4.2,2025-05-30
15,116,Ali,Delhi,Phone,Cash,28000,2,4.1,2025-03-18
16,117,Sara,Lucknow,Laptop,UPI,78000,1,4.8,2025-04-02
17,118,John,Mumbai,Tablet,Card,33000,3,4.0,2025-05-10
18,119,Emma,Delhi,Laptop,UPI,72000,2,4.9,2025-06-22
19,120,Fatima,Pune,Phone,Cash,26000,2,4.2,2025-02-18

In [3]:
#task 1 data inspection
df.head(5)
df.shape
#row:20,column:9
df.columns
#columns=['Order_ID', 'Customer', 'City', 'Category', 'Payment', 'Revenue','Quantity', 'Rating', 'Order_Date']
df.dtypes
#data type | columns
#object:customer,City,Category,Payment
#int64:Revenue,quantity
#float:Rating
#Date_time:Order_date

Order_ID               int64
Customer              object
City                  object
Category              object
Payment               object
Revenue                int64
Quantity               int64
Rating               float64
Order_Date    datetime64[ns]
dtype: object

In [4]:
#checking duplicates
df.duplicated().sum()
df['Order_ID'].duplicated().sum()
#There are no duplicates

np.int64(0)

In [5]:
#checking missing values
df.isna().sum()
#There are no missing values either

Order_ID      0
Customer      0
City          0
Category      0
Payment       0
Revenue       0
Quantity      0
Rating        0
Order_Date    0
dtype: int64

In [6]:
#task 2 Business summary
#A.)statistical summary
#1. Numeric column
df[['Revenue','Rating','Quantity']].describe()
#Average revenue:49700
#maximum revenue: 90000,min revenue: 20000
#there seem to have no outlier or exceeding or lesser value in revenue column from mean ,max and min
#average rating: 4.43,max rating:4.9,min rating:3.9
#From ratings we can conclude that ou company performs from good to excellent in market among customers
#total 20 products are sold off from this dataset,those 20 orders are placed by 19 customers

            Revenue     Rating   Quantity
count     20.000000  20.000000  20.000000
mean   49700.000000   4.430000   2.300000
std    23579.875452   0.343511   1.080935
min    20000.000000   3.900000   1.000000
25%    30000.000000   4.175000   2.000000
50%    40000.000000   4.350000   2.000000
75%    72750.000000   4.800000   3.000000
max    90000.000000   4.900000   5.000000

In [7]:
df['City'].unique()
#cities our company are in :['Delhi', 'Mumbai', 'Pune', 'Lucknow']
df['Category'].unique()
#The products our company sold off : ['Laptop', 'Phone', 'Tablet']

array(['Laptop', 'Phone', 'Tablet'], dtype=object)

In [8]:
#task3 Product analysis
df.groupby('Category')['Revenue'].sum().idxmax()
#Sir laptop generated the highest revenue of 610000
df.groupby('Category')['Quantity'].sum()
#sir, Phone sold at the highest quantity {
#Laptop    13
#Phone     15
#Tablet    18}
df.groupby('Category')['Rating'].mean()
#Laptop has the highest average rating category with 4.8 avg rating i.e., more tha phone an tablet rating
#4.18 as both respectively

Category
Laptop    4.800000
Phone     4.185714
Tablet    4.180000
Name: Rating, dtype: float64

In [9]:
#task4 city analysis
df.groupby('City')['Revenue'].sum().idxmax()
#Delhi generates the highest revenue of 435000,we might make our serives more flexible in delhi to increase sales
df.groupby('City')['Quantity'].sum().idxmax()
#Delhi bought the highest quantity , makes sense why the revenue of delhi is highest
df.groupby('City')['Revenue'].mean()
#City    |  average
#Delhi      54375.000000
#Lucknow    42666.666667
#Mumbai     57600.000000
#Pune       35750.000000
df.groupby('City')['Order_ID'].count()
#City    | orders 
#Delhi      8
#Lucknow    3
#Mumbai     5
#Pune       4
#overall , Delhi for our company is milestone for grwoth but , it tells us that 
#we have to improve our services and marketing in other cities

City
Delhi      8
Lucknow    3
Mumbai     5
Pune       4
Name: Order_ID, dtype: int64

In [10]:
#task5 Customer analysis
df.groupby('Customer')['Revenue'].sum()
#Ali contributes the highest revenue , hence , he is the highest spending customer
df.groupby('Customer')['Order_ID'].count().idxmax()
#Ali has the total of 4 orders , he placed most of the orders from our company
df.groupby('Customer')['Revenue'].mean()
#most of the customer on average spend bw (522000 to 56000) ,
#so the product liwes bw this range has more sale 

#We should give ALI offer for his next order
# we must focus on the quality of product liwes in prices bw 52000 to 56000

Customer
Ali       53250.000000
David     52500.000000
Emma      42333.333333
Fatima    52000.000000
John      52666.666667
Kabir     33500.000000
Sara      56000.000000
Name: Revenue, dtype: float64

In [11]:
#task 6 Payment analysis
df.groupby('Payment')['Revenue'].sum().idxmax()
#UPI method generates highest total revenue
df.groupby('Payment')['Order_ID'].count()
#total order placed by cash and card = 6 and UPI = 8
df.groupby('Payment')['Rating'].mean()
#Avg ratig for card and cash= 4.3 whie of UPI = 4.5

#The UPI payment method seems strong and has a big hand in generating hightes revenue and excellent rating

Payment
Card    4.300000
Cash    4.383333
UPI     4.562500
Name: Rating, dtype: float64

In [12]:
#task 7 Monthly trend
df.groupby(df['Order_Date'].dt.month_name())['Revenue'].sum()
#June has the highest revenue302000 while other months are bw 130000 to 170000
df.groupby(df['Order_Date'].dt.month_name())['Quantity'].sum()
#In may the quntity sold is highest but its revenue is still less 170000 in compariosn to june with 302000
df.groupby(df['Order_Date'].dt.month_name())['Order_ID'].count()
#june and may performs better in revenue , quantity and order placedwhile other months are on nearly 
#same scale in all aspect

Order_Date
April       3
February    3
January     2
June        5
March       3
May         4
Name: Order_ID, dtype: int64

In [13]:
#task 8 Dashboard
dash=pd.pivot_table(df,index='City',columns='Category',values='Revenue',aggfunc='sum')
dash

Category  Laptop  Phone  Tablet
City
Delhi     302000  58000   75000
Lucknow    78000  20000   30000
Mumbai    170000  85000   33000
Pune       60000  51000   32000

In [14]:
#task 9 crosstab
tab=pd.crosstab(df['City'],df['Payment'])
tab
#In DELHI and MUMBAI  cash and card count and Pune cash count; 2 
#IN  LUCKNOW and PUNE the card count is 1
#UPI count  in MUMBAI and PUNE is 1, LUCKNOW is 2 and DELHI 4 
#LUCKNOW cash count is zero ( people preferr there card and cash)

Payment  Card  Cash  UPI
City
Delhi       2     2    4
Lucknow     1     0    2
Mumbai      2     2    1
Pune        1     2    1

In [ ]:
#task10
#1. Three key findings
#In delhi our company performs  well so we make our services flexible there
#and increase and improve our facility and marketing in other cities
#Laptops from our company generates good amount of revenue with excellent rating so we should sell good quality laptops 
#at affordable prices
#UPI serive is most used payment method customer use to pay when they buy smtg from our company
#2. Business